### ISSUE TITLE
Compile failure on OS X 10.7.5

### ISSUE THREAD

**Issue by duboisj** [madewokherd/wine-mono#10]
I'm trying to compile on OS X 10.7.5, but getting failures.  The failure is: 

llibtool: compile:  x86_64-w64-mingw32-gcc -DPACKAGE_NAME=\"libgc-mono\" -DPACKAGE_TARNAME=\"libgc-mono\" -DPACKAGE_VERSION=\"6.6\" "-DPACKAGE_STRING=\"libgc-mono 6.6\"" -DPACKAGE_BUGREPORT=\"Hans_Boehm@hp.com\" -DGC_WIN32_THREADS=1 -DNO_GETENV=1 -DGC_INSIDE_DLL=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -DSILENT=1 -DNO_SIGNALS=1 -DNO_EXECUTE_PERMISSION=1 -DJAVA_FINALIZATION=1 -DGC_GCJ_SUPPORT=1 -DATOMIC_UNCOLLECTABLE=1 -D_IN_LIBGC=1 -I./.. -I../../mono/libgc/.. -I../../mono/libgc/include -DWINVER=0x0500 -D_WIN32_WINNT=0x0500 -D_WIN32_IE=0x0501 -D_UNICODE -DUNICODE -DWIN32_THREADS -DFD_SETSIZE=1024 -DGC_NOT_DLL -D__default_codegen__ -g -mno-tls-direct-seg-refs -MT alloc.lo -MD -MP -MF .deps/alloc.Tpo -c ../../mono/libgc/alloc.c  -DDLL_EXPORT -DPIC -o .libs/alloc.o
In file included from ../../mono/libgc/include/private/gc_priv.h:46:0,
                 from ../../mono/libgc/alloc.c:19:
../../mono/libgc/include/private/../gc.h:64:28: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'GC_word'

The compiler I'm using is 4.5.1: 

[Vitellius:~/bin/mingw-w64/bin] duboisj[0]% ./x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (duboisj-for-mingw-w64-build - GCC 4.5.1 x86_64-w64-mingw32) 4.5.1
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
